{% set name = "weightwatcher" %}
{% set version = "0.7.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/calculatedcontent/weightwatcher/archive/{{ version }}.tar.gz
  sha256: e606b1ba25b9bf7f3f9af34ecdec94d0a6adfb92762f2089cc28cc5f5c85d35e

build:
  number: 1
  entry_points:
    - weightwatcher = weightwatcher:main
  noarch: python
  script: |
    python -c "import os; os.makedirs('weightwatcher', exist_ok=True); with open('weightwatcher/constants.py', 'a') as f: f.write('DEFAULT_PEFT = False\n'); with open('weightwatcher/__init__.py', 'a') as f: f.write('from .weightwatcher import main\n')"
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base
    - matplotlib-inline
    - powerlaw
    - scikit-learn
    - safetensors
    - tqdm

test:
  imports:
    - weightwatcher
  commands:
    - pip check
    - weightwatcher --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A tool for analyzing and visualizing the weight distribution of neural networks.
  home: https://github.com/calculatedcontent/weightwatcher
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sarthakpati
